import React, { useState } from 'react';
import { useStore } from '../context/StoreContext';
import { Flame, Eye, Map, Compass, Grid, AlertCircle, Sparkles } from 'lucide-react';

const ZONE_POSITIONS = [
  { top: 'top-[20%]', left: 'left-[24%]', blobClass: 'w-24 h-24 bg-red-400/40 blur-2xl rounded-full', textClass: 'absolute top-[22%] left-[26%] text-purple-950 text-[10px] font-mono font-bold bg-white px-2 py-1 rounded-md border border-purple-200 cursor-pointer pointer-events-none z-10 shadow-sm leading-none max-w-[130px] truncate' },
  { top: 'top-[48%]', left: 'left-[54%]', blobClass: 'w-32 h-32 bg-purple-400/45 blur-3xl rounded-full', textClass: 'absolute top-[48%] left-[58%] text-purple-950 text-[10px] font-mono font-bold bg-white px-2 py-1 rounded-md border border-purple-200 cursor-pointer pointer-events-none z-10 shadow-sm leading-none max-w-[130px] truncate' },
  { top: 'bottom-[24%]', left: 'left-[16%]', blobClass: 'w-20 h-20 bg-purple-500/35 blur-2xl rounded-full', textClass: 'absolute bottom-[28%] left-[18%] text-purple-950 text-[10px] font-mono font-bold bg-white px-2 py-1 rounded-md border border-purple-200 cursor-pointer pointer-events-none z-10 shadow-sm leading-none max-w-[130px] truncate' },
  { top: 'top-[24%]', left: 'right-[20%]', blobClass: 'w-28 h-28 bg-amber-500/40 blur-3xl rounded-full', textClass: 'absolute top-[28%] right-[22%] text-purple-950 text-[10px] font-mono font-bold bg-white px-2 py-1 rounded-md border border-purple-200 cursor-pointer pointer-events-none z-10 shadow-sm leading-none max-w-[130px] truncate' },
  { top: 'bottom-[16%]', left: 'right-[20%]', blobClass: 'w-40 h-16 bg-purple-600/35 blur-2xl rounded', textClass: 'absolute bottom-[22%] right-[24%] text-purple-950 text-[10px] font-mono font-bold bg-white px-2 py-1 rounded-md border border-purple-200 cursor-pointer pointer-events-none z-10 shadow-sm leading-none max-w-[130px] truncate' },
];

export const HeatmapSection: React.FC = () => {
  const { heatmap, activeStore } = useStore();
  const [selectedZone, setSelectedZone] = useState<string | null>('z1');

  const activeZoneData = heatmap.find(z => z.id === selectedZone);

  return (
    <div className="space-y-6 font-sans text-purple-950 animate-fadeIn bg-transparent pb-10">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2">
        <div>
          <h2 className="text-xl md:text-2xl font-bold text-purple-950 tracking-tight">CCTV Foot-Traffic Heatmap</h2>
          <p className="text-xs text-purple-705">
            Real-time visual occupancy and department dwell-time overlays generated by camera tracking at <span className="text-purple-700 font-extrabold">{activeStore.name}</span>
          </p>
        </div>
        
        {/* Floor picker selection pill layout */}
        <div className="flex gap-1 bg-[#f5f3ff] border border-purple-200 p-1 rounded-lg text-[10px] font-mono font-bold text-purple-700 shadow-xxs">
          <button className="bg-purple-600 text-white px-3 py-1 rounded-md shadow-xs">FLOOR 01</button>
          <button className="px-3 py-1 hover:text-purple-900 transition-colors">FLOOR 02</button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">

        {/* Left Column: Interactive Floorplan Layout Map */}
        <div className="lg:col-span-8 bg-white border border-purple-100 rounded-xl p-5 flex flex-col justify-between h-[420px] relative overflow-hidden shadow-xs group">
          
          {/* Header info */}
          <div className="flex justify-between items-center z-10">
            <span className="text-[10px] font-bold uppercase tracking-wider text-purple-600 flex items-center gap-1.5 font-mono">
              <Compass className="w-4 h-4 text-purple-650 shrink-0" />
              <span>Camera Spatial Projection Map</span>
            </span>
            <span className="text-[10px] font-mono text-emerald-700 bg-emerald-50 border border-emerald-250 px-2.5 py-0.5 rounded-lg font-bold">
              Live Camera Mapping Active
            </span>
          </div>

          {/* Interactive schematic map with heat zones absolute layout */}
          <div className="flex-1 rounded-xl bg-purple-50/40 border border-purple-100 relative my-4 overflow-hidden flex items-center justify-center">
            {/* Grid pattern background */}
            <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0MCIgaGVpZ2h0PSI0MCI+PGNpcmNsZSBjeD0iMjAiIGN5PSIyMCIgcj0iMSIgZmlsbD0icmdiYSgxMzksOTIsMjQ2LDAuMTUpIi8+PCvc3ZnPg==')] opacity-60"></div>

            {/* Simulated Heatmap Blobs and Text Labels dynamically loaded */}
            {heatmap.map((zone, idx) => {
              const pos = ZONE_POSITIONS[idx] || ZONE_POSITIONS[idx % ZONE_POSITIONS.length];
              
              return (
                <React.Fragment key={zone.id}>
                  <div 
                    onClick={() => setSelectedZone(zone.id)}
                    className={`absolute ${pos.top} ${pos.left} ${pos.blobClass} cursor-pointer hover:scale-105 transition-all active:scale-95`}
                  />
                  <span 
                    onClick={() => setSelectedZone(zone.id)}
                    className={`${pos.textClass} hover:border-purple-400 hover:bg-purple-50/40 cursor-pointer transition-all`}
                  >
                    {zone.name.split(' (')[0].split(' & ')[0]}
                  </span>
                </React.Fragment>
              );
            })}

            <div className="absolute bottom-3 left-3 flex items-center gap-1.5 bg-white border border-purple-200 px-2.5 py-1.5 rounded-lg text-[10px] text-purple-700 shadow-xs font-bold font-mono">
              <Grid className="w-3.5 h-3.5 text-purple-500" />
              <span>Scale: Cell Grid 0.5m x 0.5m Projection</span>
            </div>
          </div>

          <p className="text-[10px] text-purple-405 text-center font-mono font-bold">
            ℹ️ Pro tip: Click any color overlay on the schematic draft to analyze detailed statistics on the right panel.
          </p>
        </div>

        {/* Right Column: Zone Occupancy Index Ledger */}
        <div className="lg:col-span-4 space-y-4">
          <div className="bg-white border border-purple-100 rounded-xl p-5 space-y-4 h-[420px] overflow-y-auto shadow-xs">
            <h3 className="font-bold text-purple-950 text-sm flex items-center gap-2 border-b border-purple-100 pb-2">
              <Flame className="w-4.5 h-4.5 text-purple-600" />
              <span>Department Occupancies</span>
            </h3>

            <div className="space-y-2">
              {heatmap.map((zone) => {
                const isSelected = selectedZone === zone.id;
                return (
                  <button
                    key={zone.id}
                    onClick={() => setSelectedZone(zone.id)}
                    className={`w-full text-left p-3 rounded-xl border transition-all flex justify-between items-center cursor-pointer ${
                      isSelected 
                        ? 'bg-purple-100/70 border-purple-400 shadow-xs scale-[0.99]' 
                        : 'bg-purple-50/40 border-purple-100 hover:border-purple-250'
                    }`}
                  >
                    <div className="space-y-0.5">
                      <span className="text-xs font-bold text-purple-950 block">{zone.name}</span>
                      <span className="text-[10px] font-mono font-bold text-purple-500 leading-none">
                        Frequency: {zone.visitFrequency} entries
                      </span>
                    </div>

                    <div className="text-right">
                      <span className="text-xs font-mono font-extrabold text-purple-700 block">{zone.avgDwellTime}</span>
                      <span className="text-[9px] text-purple-400 block font-bold">Avg Dwell</span>
                    </div>
                  </button>
                );
              })}
            </div>

            {/* Selected Zone Deep stats drawer */}
            {activeZoneData && (
              <div className="p-3.5 bg-purple-50/50 border border-purple-150 rounded-xl space-y-1.5 animate-fadeIn shadow-inner">
                <span className="text-[10px] font-mono text-purple-400 uppercase font-extrabold block">Deep Analyzer</span>
                <p className="text-xs font-bold text-purple-950 leading-none">{activeZoneData.name} Segment</p>
                <div className="grid grid-cols-2 gap-2 text-[10px] font-mono pt-1">
                  <div className="bg-white p-1.5 rounded-lg text-purple-700 border border-purple-100/80 font-bold">
                    Popularity: <strong className="text-purple-950">{activeZoneData.popularityScore}%</strong>
                  </div>
                  <div className="bg-white p-1.5 rounded-lg text-purple-700 border border-purple-100/80 font-bold">
                    Zone State: <strong className="text-emerald-700">Active</strong>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>

      </div>
    </div>
  );
};
